### ISSUE TITLE
Test suite fails on OS X

### ISSUE THREAD

**Issue by Gabriella439** [nh2/shared-memory#1]
When I run `cabal test` on OS X, I get the following test failure:

```
Running 1 test suites...
Test suite test-shared-memory-example: RUNNING...
test-shared-memory-example: shmOpen: invalid argument (Invalid argument)
Test suite test-shared-memory-example: FAIL
Test suite logged to:
dist/test/shared-memory-0.1.0.0-test-shared-memory-example.log
0 of 1 test suites (0 of 1 test cases) passed.
```

I've actually been using the library just fine on OS X, so this test failure is harmless from my point of view.  The only reason I even noticed this at all is because I've been test driving Nix and Nix tries to run all tests before committing a build product.  I just wanted to point it out just in case.

**Comment by nh2** [comment]
Hi Gabriel,

this is confusing me: According to [this OSX `shm_open` man page](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/shm_open.2.html) the only listed reason for `Invalid argument` is:

```
[EINVAL]           The shm_open() operation is not supported.
```

which suggests that it should either work, or not at all. Are the OSX where you use it just fine, and the one where you run Nix on the same OSX versions?

**Comment by Gabriella439** [comment]
Oh wait, my mistake!  I actually wasn't getting it to work on OS X.  I was confusing it with another program that didn't use this command.  So in this case it's probably just a case of the operation not being supported and the test failure is doing the right thing.

I'll go ahead and close this issue, then.

**Comment by nh2** [comment]
Out of interest, do you know if OSX should support `shm_open`? Seems weird that there's a man page but the syscall doesn't work.

**Comment by Gabriella439** [comment]
I don't know :\
